# NKeconomy

# MySQL connection (required)
use-mysql: false
table-prefix: NKeco_
host: localhost
port: 3306
dbName: minecraft_dev
user: root
password: 

# Options
server-name: 'world'
start-amount: 100
currency: Lumi